theme: jekyll-theme-minimal
title: Marco Zanini
description: "<em>Software Engineer based in Seattle, WA</em><br>
<a href="https://github.com/mzanini/">GitHub</a> / <a href="https://www.linkedin.com/in/marco-zanini">LinkedIn</a>"

