theme: jekyll-theme-minimal
title: Marco Zanini
description: "_Software Engineer based in Seattle, WA_ <br>
[GitHub](https://github.com/mzanini/) / [LinkedIn](https://www.linkedin.com/in/marco-zanini)"

